In [1]:
import pandas as pd

#player data for every game in the 2021-22
dfPlayers = pd.read_csv('games_by_players.csv', dtype='string')

#used to replace team_id with the team name
dfTeams = pd.read_csv('games_by_teams.csv', dtype='string')

#used to clean dfPlayers to only events listed as a "Major" or "World Championship"
dfMain = pd.read_csv('main.csv', dtype='string')

#cleans dfPlayer to only events listed as a "Major" or "World Championship"
dfMain = dfMain[(dfMain['event'] == 'Major') | (dfMain['event'] == 'World Championship')]
gameData = []
for i in range(len(dfMain)):
    mainId = dfMain.iloc[i]['game_id']
    if mainId in dfPlayers['game_id'].values:
        gameData.append(dfPlayers.loc[dfPlayers['game_id'] == mainId])
dfGames = pd.concat(gameData)
dfGames

,game_id,color,team_id,team_region,player_id,player_tag,core_shots,core_goals,core_saves,core_assists,...,car_id,car_name,steering_sensitivity,camera_fov,camera_height,camera_pitch,camera_distance,camera_stiffness,camera_swivel_speed,camera_transition_speed
35922,61b0e7c7da9d7ca1c7ba35c4,blue,6020bc70f1e4807cc70023a0,North America,5f3d8fdd95f40596eae23d6f,GarrettG,6,0,3,0,...,4284,Fennec,1.3,110.0,110.0,-3.0,270.0,0.45,6.9,1.2
35923,61b0e7c7da9d7ca1c7ba35c4,blue,6020bc70f1e4807cc70023a0,North America,5f3d8fdd95f40596eae23dcf,jstn.,3,0,0,0,...,23,Octane,1.3,110.0,100.0,-3.0,270.0,0.45,4.7,1.3
35924,61b0e7c7da9d7ca1c7ba35c4,blue,6020bc70f1e4807cc70023a0,North America,5f3d8fdd95f40596eae23d95,Squishy,1,0,1,0,...,23,Octane,1.3,110.0,100.0,-3.0,270.0,0.45,4.7,1.2
35925,61b0e7c7da9d7ca1c7ba35c4,orange,6020bce6f1e4807cc70071af,South America,5f3d8fdd95f40596eae23f5e,snipjz,1,0,3,1,...,23,Octane,1.7,110.0,100.0,-4.0,270.0,0.45,5.0,1.6
35926,61b0e7c7da9d7ca1c7ba35c4,orange,6020bce6f1e4807cc70071af,South America,5fbda6e016fbe0e46966b13e,Aztromick,2,0,2,0,...,23,Octane,2.2,110.0,100.0,-3.0,270.0,0.3,10.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106790,62f99ac9c437fde7e02daf25,blue,6020bd98f1e4807cc700dc74,Europe,5f3d8fdd95f40596eae240d2,M0nkey M00n,4,1,0,2,...,23,Octane,3.83,109.0,110.0,-3.0,260.0,0.6,4.0,1.1
106791,62f99ac9c437fde7e02daf25,blue,6020bd98f1e4807cc700dc74,Europe,5fd40fc10e831f1d52bd96a5,Seikoo,3,0,2,1,...,4284,Fennec,1.8,110.0,100.0,-3.0,240.0,0.7,4.2,1.4
106792,62f99ac9c437fde7e02daf25,orange,6020bc70f1e4807cc70023a5,North America,5f3d8fdd95f40596eae23d8f,JKnaps,2,0,3,0,...,4284,Fennec,2.0,109.0,100.0,-4.0,270.0,0.4,3.1,1.3
106793,62f99ac9c437fde7e02daf25,orange,6020bc70f1e4807cc70023a5,North America,5f3d8fdd95f40596eae23dba,Chicago,2,0,2,0,...,23,Octane,3.5,110.0,100.0,-3.0,270.0,0.4,10.0,1.2
106794,62f99ac9c437fde7e02daf25,orange,6020bc70f1e4807cc70023a5,North America,5f3d8fdd95f40596eae23fe6,Atomic,1,0,0,0,...,23,Octane,3.5,110.0,100.0,-3.0,270.0,0.4,10.0,1.2

In [2]:
#replaces team_id in df with the team name
dfTeams = dfTeams.drop_duplicates('team_id')

teamDict = {}
teamNames = []
win = []
loss = []
for i in range(len(dfTeams)):
    teamDict[dfTeams.iloc[i]['team_id']] = dfTeams.iloc[i]['team_name']

for i in range(len(dfGames)):
    teamNames.append(teamDict[dfGames.iloc[i]['team_id']])
    if dfGames.iloc[i]['winner'] == 'False':
        win.append(0)
        loss.append(1)
    else:
        win.append(1)
        loss.append(0)
dfGames['team_name'] = teamNames
dfGames['win'] = win
dfGames['loss'] = loss
df = dfGames.reset_index()
df= df[['game_id', 'team_name', 'player_tag', 'core_shots', 'core_goals', 'win', 'loss']]
df['core_shots'] = pd.to_numeric(df['core_shots'])
df

,game_id,team_name,player_tag,core_shots,core_goals,win,loss
0,61b0e7c7da9d7ca1c7ba35c4,NRG ESPORTS,GarrettG,6,0,0,1
1,61b0e7c7da9d7ca1c7ba35c4,NRG ESPORTS,jstn.,3,0,0,1
2,61b0e7c7da9d7ca1c7ba35c4,NRG ESPORTS,Squishy,1,0,0,1
3,61b0e7c7da9d7ca1c7ba35c4,ERA ETERNITY,snipjz,1,0,1,0
4,61b0e7c7da9d7ca1c7ba35c4,ERA ETERNITY,Aztromick,2,0,1,0
...,...,...,...,...,...,...,...
4729,62f99ac9c437fde7e02daf25,TEAM BDS,M0nkey M00n,4,1,1,0
4730,62f99ac9c437fde7e02daf25,TEAM BDS,Seikoo,3,0,1,0
4731,62f99ac9c437fde7e02daf25,G2 ESPORTS,JKnaps,2,0,0,1
4732,62f99ac9c437fde7e02daf25,G2 ESPORTS,Chicago,2,0,0,1
4733,62f99ac9c437fde7e02daf25,G2 ESPORTS,Atomic,1,0,0,1

In [3]:
def playerShotWinPct (player):
    playerDf = df[df['player_tag'] == player]
    winCount = playerDf.groupby('core_shots').agg('sum').reset_index()
    winPct = []
    for i in range(len(winCount)):
        winPct.append(winCount.iloc[i]['win']/(winCount.iloc[i]['win'] + winCount.iloc[i]['loss']))
    winCount['winPct'] = winPct
    return winCount
playerShotWinPct('Darth.')

   core_shots  win  loss  winPct
0           0    0     3     0.0
1           1    0     9     0.0
2           2    1     1     0.5
3           3    1     0     1.0
4           4    2     0     1.0
5           5    1     0     1.0

In [8]:
dfPlayers = df.groupby('player_tag').agg('count').reset_index()
playerRegressionDf = dfPlayers[['player_tag']]
playerRegressionDf
winSlope = []

from sklearn.linear_model import LinearRegression

for player in playerRegressionDf['player_tag']:
    dfSlope = playerShotWinPct(player)
    model = LinearRegression()
    model = model.fit(dfSlope[['core_shots']], dfSlope['winPct'])
    winSlope.append(float(model.coef_))
playerRegressionDf['winSlope'] = winSlope
playerRegressionDf.sort_values(by=['winSlope'], ascending=False).head(10)

/var/folders/j_/tw0g51hj5zv9j4jgk1s6hmnm0000gn/T/ipykernel_65068/382845985.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegressionDf['winSlope'] = winSlope

     player_tag  winSlope
26       Darth.  0.242857
92        sigms  0.201255
3      AcroniK.  0.185109
68       Tenhow  0.182857
61         Shad  0.176327
19     Catalysm  0.172477
45         M7sN  0.155612
81          ivn  0.152041
58  Scrub Killa  0.151024
28      Express  0.146508